/// Database of all registered users for the championship.
/// Hardcoded for demo purposes.
final registeredUsers = ['1','2',
'3','4'
];

/// Database of auth bearer tokens for all registered users of championship.
/// To be generated by the server on the fly, hardcoded for demo purposes.
final Map<String,String> secretCodes = {
  '1':'itissimplyone',
  '2':'thisistoomuch',
  '3': 'threedeeforchange',
  '4': 'quatroformaggi',
};

/// Record of all the users who are waiting in a virtual lobby
final List<Map<String,String>> userLobby = [];

/// Record of all the users who are still competing in the championship.
final List<Map<String,String>> competingPlayers = [];

/// Record of all users joined but no longer competing in the championship.
final List<Map<String,String>> noncompetingPlayer = [];

// final List<Map<String,String>> players = [];

/// Database of all drawn games
final Map<String,Map<String,dynamic>> games = {};

/// Database of game moves
final List<Map<String,dynamic>> gameMoves = [];

///Used to define points to be scored in a game
const int kPointsToWinAGame = 1; //5